### ISSUE TITLE
Usage

### ISSUE THREAD

**Issue by elsabio** [ronniedong/Expect-for-Java#1]
OK, Not really an issue but I'm having some problems finding how to contact the author.

This nice little class has saved me a few days in a test harness and I'd like to continue using it.

I need to understand if the discalaimer posted is the full extent of the license you want to assign to this software or if you plan to elect to use something like Apache/BSD/LGPL/Open or whatever before I feel comfortable doing that.

Mark.

**Comment by ronniedong** [comment]
Hi Mark, I used the disclaimer to void my liabilities. I have not decided a license but I will use one that allows the use/modify of this code freely.
