### ISSUE TITLE
Import Issue

### ISSUE THREAD

**Issue by codered** [ronniedong/Expect-for-Java#2]
I am trying to use Expect.java in my program using Netbeans. I find that there are a lot of errors for packages. 

My question is, what environment is this script designed to run? Linux? Windows? What version of Java is supported ( I am using 1.6). 

I am an avid developer of applications and I can help out as this a useful library.

Thanks :) 

-Harsh

**Comment by ronniedong** [comment]
Hi Harsh, Please take a look at the readme file, log4j is needed for dependency. The code was tested with Java 1.6 in Linux and Solaris. If you find any issue in Windows please let me know.
