### ISSUE TITLE
Usage with Apache SSHD

### ISSUE THREAD

**Issue by syepes** [ronniedong/Expect-for-Java#3]
Hello,

I have just found you Expect library and was wondering if you have tested it with the apache sshd library  (http://mina.apache.org/sshd-project)?

I personally have not been able to make it work, here is an example:

```
import org.apache.sshd.*

SshClient client = SshClient.setUpDefaultClient()
ClientSession session = client.connect(host, port).await().getSession()
session.authPassword(user, password).await().isSuccess()
ClientChannel channel = session.createChannel(ClientChannel.CHANNEL_SHELL)

channel.setIn(new ByteArrayInputStream())
channel.setOut(new ByteArrayOutputStream())
channel.setErr(new ByteArrayOutputStream())
channel.open()

Expect expect = new Expect(channel.getIn(), channel.getOut())
expect.send("ls\n")
expect.expect("$")

expect.send("exit\n")
expect.expectEOF()
expect.close()

channel.waitFor(ClientChannel.CLOSED, 0)
channel.close(false)
client.stop()
```

Thanks in advance for any suggestion on how I could make it wotk.

Best regards,
Sebas

**Comment by ronniedong** [comment]
Hello Sebas,

Is there any particular reason to choose apache sshd? I am not sure how it works, but is it supposed to be used with ByteArrayInputStream? Have you tried to write/read with the ClientChannel? Besides, you need to call System.out.println(expect.before + expect.match); to see the output of your command.

On the other hand I suggest using JSch at http://www.jcraft.com/jsch/ which I use in the examples.

Ronnie

**Comment by syepes** [comment]
I have finally decided to use the JSch library and it works like a charm.

The only thing I am now missing is some way to capture the full output of the sent command, some thing just like the ".before and .match" but that stores the complete output of the last sent command ".fullOutput".

Do you think it would be possible implement this?

Best regards,
Sebas
