### ISSUE TITLE
Provide jar package for Expect.java

### ISSUE THREAD

**Issue by recyard** [ronniedong/Expect-for-Java#9]
Hi ronnie, thanks for the great work on Expect-for-Java. I wonder, would you provide a jar package for this project, since I don't want to touch the main code. If I put this in my code, I need add a line "package ..." to Expect.java, not sure about the license issue. A standalone jar would be better for my situation. Thanks.

**Comment by ronniedong** [comment]
Hi recyard,

Feel free to build a jar based on the source code, the license on this project is quite open.

Reasons I do not provide a jar: 1. it might be out-dated; 2. I want to expose all internal implementations (the code is intended for the user to customize)

It is fairly easy to build a jar file in eclipse.

Thanks.
Ronnie
